site_name: ACTM-HAIKU
site_author: Michael Planer for BAE Systems, Inc
theme:
    name: readthedocs

nav:
    - 'index.md'
    - 'data_models.md'
    - 'koopman.md'
    - 'analyses.md'
    - 'metrics.md'
    - 'software_framework.md'
    - 'Tutorials':
        - 'Configure HAIKU': 'Tutorials/configure_haiku.md'
        - 'Running HAIKU': 'Tutorials/running_the_code.md'
        - 'Quickstart': 'Tutorials/quickstart.md'
    - "Results":
        - "Results": 'Results/initial_motivation_results.md'
    - 'about.md'