site_name: ACTM-HAIKU
site_author: Michael Planer for BAE Systems, inc
theme:
    name: readthedocs
    
nav:
    - 'index.md'
    - 'data_models.md'
    - 'koopman.md'
    - 'analyses.md'
    - 'results.md'
    - 'about.md'